version: '2' #cdocker-compose版本
services: #所有服务集合
  mysql: #数据库服务
    image: mysql:5.7 #镜像源
    volumes: #数据卷,挂载目录
      - "./docker/mysql/data:/var/lib/mysql" #宿主机目录:容器目录
    ports: #与宿主进的端口映射
      - "3306:3306" #宿主机端口:容器端口
    restart: always #异常退出后重启
    env_file: .env #导入配置变量
    environment: #容器中环境变量
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}" #数据库root用户密码
      MYSQL_DATABASE: "${DB_DATABASE}" #新创建数据库名称
      MYSQL_USER: "${DB_USERNAME}" #数据库用户名
      MYSQL_PASSWORD: "${DB_PASSWORD}" #数据库密码
  tool: #工具容器(包含:composer,npm,cnpm,git,php,node...)
    build: ./docker/tool
    depends_on:
      - mysql
    volumes: #挂载php配置项
      - ".:/var/www/laravel"
      - "./docker/php-fpm/php/php-fpm.conf:/etc/php-fpm.conf"
      - "./docker/php-fpm//php/www.conf:/etc/php-fpm.d/www.conf"
      - "./docker/php-fpm//php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm//php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    links:
      - mysql:db
    entrypoint: #挂起容器不退出
      tail -f /etc/passwd
  php-fpm: #php服务
    build: ./docker/php-fpm
    depends_on:
      - tool
    volumes: #挂载php配置项
      - ".:/var/www/laravel"
      - "./docker/php-fpm//php/php-fpm.conf:/etc/php-fpm.conf"
      - "./docker/php-fpm//php/www.conf:/etc/php-fpm.d/www.conf"
      - "./docker/php-fpm//php/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/php-fpm//php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini"
    links:
      - mysql:db
    restart: always
  nginx: #服务器服务
    image: nginx:1.15
    depends_on:
      - php-fpm
    volumes:
      - ".:/var/www/laravel"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "80:80"
    restart: always
    links:
      - php-fpm:php-fpm
